---
# The recorder component is storing details in a database which
# then are handled by the history component.
#
# https://www.home-assistant.io/integrations/recorder/
#
recorder:
  # Use the Core MariaDB add-on to store the recorder data in
  # e.g.: "mysql://homeassistant:PASSWORD@core-mariadb/homeassistant?charset=utf8"
  db_url: !secret recorder_db_url

  # The number of days of history to keep in the recorder database
  purge_keep_days: 30

  # How often (in days) the purge task runs
  purge_interval: 1
  
  include:    # Include everything you graph and will want to see later
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
  
  exclude:    # Eliminate anything that you never graph or refer back to
    domains:
      - automation
      - updater
    entities:
      - sun.sun
      - sensor.time
      - sensor.date_time_iso # Don't record date and time
      - sensor.yr_symbol # Ignore this as well
      - group.weather # Don't save weather 
