lights_partying_on:
  alias: Lights partying on
  sequence:
    - service: light.turn_on
      data_template:
        entity_id: light.{{['mqtt_json_light','mqtt_json_light_2']|random}}
        rgb_color: ['{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}', '{{ (range(0, 255)|random) }}']
        brightness: 250
        transition: '{{ (range(1, 3)|random) }}'