lights_mode_party_on:
  alias: Party on
  sequence:
    # - service: homeassistant.turn_off
    #   entity_id: automation.sense_lights_change
    - service: homeassistant.turn_on
      entity_id: automation.lights_partying