---
platform: "mqtt"
state_topic: "zigbee2mqtt/0x00124b00213aee2c"
availability_topic: "zigbee2mqtt/bridge/state"
brightness: true
color_temp: true
xy: true
schema: "json"
command_topic: "zigbee2mqtt/0x00124b00213aee2c/set"